### ISSUE TITLE
Start Tab recording from API

### ISSUE THREAD

**Issue by mcorner** [w69b/castify-api-docs#13]
You can start a tab recording from the API, but only if the user has pressed the screencastify extension  button once for the tab.  And this happens for every new tab.  I don't think there is a way to fix this according to the chrome docs.

However, if you do start a tab recording and they haven't pressed screencastify at least once you get an exception in JS, which is good, but the user sees a misleading error message popup.   It would be good to suppress that message and we can direct users to momentarily press the button before we try to start recording.

**Comment by Schibum** [comment]
Tab recording is currently not officially supported via the API, that's why it's not mentioned in the docs.
There is a workaround for some internal use-cases. If you have full control over the devices that your users use, then you could start Chrome with an additional commandline argument:
`--whitelisted-extension-id=mmeijimgabbpbgpdklnllpncmdofkcpn`

I'd like to learn more about your use-case for tab via API. Would support for tab recording via the picker dialog (as currently shown for desktop / window recording) help?

**Comment by Schibum** [comment]
Tab recording is now supported with `captureSource: 'tab_picker`, see [here](https://github.com/w69b/castify-api-docs/blob/master/API.md#screencastifyrecordconfig--object)
