### ISSUE TITLE
Weak security model

### ISSUE THREAD

**Issue by rstormsf** [w69b/castify-api-docs#6]
@Schibum 

If I change just 1 line of code - it gives me full access, unlimited video recording + no branding image.
:-)

**Comment by Schibum** [comment]
I'm fully aware of that. But there is no such thing as client side security anyway. So why spend much time obfuscating against piracy, that could otherwise be used to improve Screencastify?

We just believe that people out there are honest, and especially those that are capable of digging though code can appreciate the work of others. 
You'll know that using Screencastify like this, you won't get any updates and it can break at any time.

Feel free to use it this way personally. But I'll ask you remove the pirated copy from Github to not encourage others to do that, who might not be fully aware of the consequences.

**Comment by rstormsf** [comment]
@Schibum 
Got it! I'll remove the repo now. Sorry about that.

**UPDATE:** it's done. Do you want me to fully remove the repo or is it ok to leave git commit history?

As I said, there is way to make more secure by having this logic inside of C++ pnacl.

**Comment by Schibum** [comment]
Thank you for understanding. I'd be great if you could remove the repo completely, or make it private.
